<?php

$filter_tags = [
    "Source Books" => [
        "core"            => "Core",
        "high-fantasy"    => "High Fantasy",
        "natural-fantasy" => "Natural Fantasy",
        "techno-fantasy"  => "Techno Fantasy",
    ],

    "Classes" => [
        "any-class"    => "Any Class",
        "arcanist"     => "Arcanist",
        "chanter"      => "Chanter",
        "chimerist"    => "Chimerist",
        "commander"    => "Commander",
        "dancer"       => "Dancer",
        "darkblade"    => "Darkblade",
        "elementalist" => "Elementalist",
        "entropist"    => "Entropist",
        "esper"        => "Esper",
        "floralist"    => "Floralist",
        "fury"         => "Fury",
        "gourmet"      => "Gourmet",
        "guardian"     => "Guardian",
        "invoker"      => "Invoker",
        "loremaster"   => "Loremaster",
        "merchant"     => "Merchant",
        "mutant"       => "Mutant",
        "orator"       => "Orator",
        "pilot"        => "Pilot",
        "rogue"        => "Rogue",
        "sharpshooter" => "Sharpshooter",
        "spiritist"    => "Spiritist",
        "symbolist"    => "Symbolist",
        "tinkerer"     => "Tinkerer",
        "wayfarer"     => "Wayfarer",
        "weaponmaster" => "Weaponmaster",
    ],

    "Class Mechanics" => [
        "arcana"      => "Arcana",
        "companion"   => "Companion",
        "dance"       => "Dances",
        "garden"      => "Garden",
        "gift"        => "Gifts",
        "ingredient"  => "Ingredients",
        "invocation"  => "Invocations",
        "module"      => "Modules",
        "symbol"      => "Symbols",
        "therioform"  => "Therioforms",
        "trade-point" => "Trade Points",
        "vehicle"     => "Vehicles",
        "verse"       => "Verses",
    ],

    "Turn Actions" => [
        "attack"       => "Attack",
        "equipment"    => "Equipment",
        "guard"        => "Guard",
        "hinder"       => "Hinder",
        "inventory"    => "Inventory",
        "objective"    => "Objective",
        "skill"        => "Skill",
        "spell"        => "Spell",
        "study"        => "Study",
    ],

    "Game Mechanics" => [
        "bond"         => "Bond",
        "clock"        => "Clock",
        "crisis"       => "Crisis",
        "critical"     => "Critical Success",
        "fabula-point" => "Fabula Point",
        "fumble"       => "Fumble",
        "ritual"       => "Ritual",
        "travel"       => "Travel",
        "zenit"        => "Zenit",
    ],

    "Attributes & Stats" => [
        "DEX"           => "Dexterity (DEX)",
        "INS"           => "Insight (INS)",
        "MIG"           => "Might (MIG)",
        "WLP"           => "Willpower (WLP)",
        "hp"            => "Hit Points",
        "mp"            => "Mind Points",
        "ip"            => "Inventory Points",
        "defense"       => "Defense",
        "magic-defense" => "Magic Defense",
        "initiative"    => "Initiative",
    ],

    "Damage Affinities" => [
        "absorption"    => "Absorption",
        "immunity"      => "Immunity",
        "resistance"    => "Resistance",
        "vulnerability" => "Vulnerability",
    ],

    "Damage Types" => [
        "air"      => "Air",
        "bolt"     => "Bolt",
        "dark"     => "Dark",
        "earth"    => "Earth",
        "fire"     => "Fire",
        "ice"      => "Ice",
        "light"    => "Light",
        "physical" => "Physical",
        "poison"   => "Poison",
        "untyped"  => "Untyped",
    ],

    "Status Conditions" => [
        "dazed"     => "Dazed",
        "shaken"    => "Shaken",
        "slow"      => "Slow",
        "weak"      => "Weak",
        "enraged"   => "Enraged",
        "poisoned"  => "Poisoned",
    ],

    "Equipment Types" => [
        "basic"         => "Basic",
        "rare"          => "Rare",
        "martial"       => "Martial",
        "non-martial"   => "Non-Martial",
        "accessory"     => "Accessory",
        "armor"         => "Armor",
        "shield"        => "Shield",
        "weapon"        => "Weapon",
    ],

    "Weapon Categories" => [
        "arcane"        => "Arcane",
        "bow"           => "Bow",
        "brawling"      => "Brawling",
        "dagger"        => "Dagger",
        "firearm"       => "Firearm",
        "flail"         => "Flail",
        "heavy"         => "Heavy",
        "spear"         => "Spear",
        "sword"         => "Sword",
        "thrown"        => "Thrown",
        "one-handed"    => "One-Handed",
        "two-handed"    => "Two-Handed",
        "melee"         => "Melee",
        "ranged"        => "Ranged",
    ],

    "Creature Species" => [
        "beast"         => "Beast",
        "construct"     => "Construct",
        "demon"         => "Demon",
        "elemental"     => "Elemental",
        "humanoid"      => "Humanoid",
        "monster"       => "Monster", 
        "plant"         => "Plant",
        "undead"        => "Undead",
    ],
];