<?php

$filter_tags = [
    "Source Books" => [
        "core"            => "Core",
        "high-fantasy"    => "High Fantasy",
        "natural-fantasy" => "Natural Fantasy",
        "techno-fantasy"  => "Techno Fantasy",
    ],

    "Classes" => [
        "any-class"    => "Any Class",
        "arcanist"     => "Arcanist",
        "chanter"      => "Chanter",
        "chimerist"    => "Chimerist",
        "commander"    => "Commander",
        "dancer"       => "Dancer",
        "darkblade"    => "Darkblade",
        "elementalist" => "Elementalist",
        "entropist"    => "Entropist",
        "esper"        => "Esper",
        "floralist"    => "Floralist",
        "fury"         => "Fury",
        "gourmet"      => "Gourmet",
        "guardian"     => "Guardian",
        "invoker"      => "Invoker",
        "loremaster"   => "Loremaster",
        "merchant"     => "Merchant",
        "mutant"       => "Mutant",
        "orator"       => "Orator",
        "pilot"        => "Pilot",
        "rogue"        => "Rogue",
        "sharpshooter" => "Sharpshooter",
        "spiritist"    => "Spiritist",
        "symbolist"    => "Symbolist",
        "tinkerer"     => "Tinkerer",
        "wayfarer"     => "Wayfarer",
        "weaponmaster" => "Weaponmaster",
    ],

    "Actions & Mechanics" => [
        "attack"       => "Attack",
        "bond"         => "Bond",
        "clock"        => "Clock",
        "crisis"       => "Crisis",
        "critical"     => "Critical",
        "equipment"    => "Equipment",
        "fabula-point" => "Fabula Point",
        "fumble"       => "Fumble",
        "guard"        => "Guard",
        "hinder"       => "Hinder",
        "melee"        => "Melee",
        "objective"    => "Objective",
        "ranged"       => "Ranged",
        "skill"        => "Skill",
        "spell"        => "Spell",
        "status"       => "Status",
        "study"        => "Study",
        "travel"       => "Travel",
    ],

    "Attributes & Resources" => [
        "defense"       => "Defense",
        "DEX"           => "Dexterity (DEX)",
        "hp"            => "Hit Points",
        "initiative"    => "Initiative",
        "INS"           => "Insight (INS)",
        "ip"            => "Inventory Points",
        "magic-defense" => "Magic Defense",
        "MIG"           => "Might (MIG)",
        "mp"            => "Mind Points",
        "WLP"           => "Willpower (WLP)",
        "zenit"         => "Zenit",
    ],

    "Damage & Affinities" => [
        "absorption"    => "Absorption",
        "damage"        => "Damage",
        "immunity"      => "Immunity",
        "resistance"    => "Resistance",
        "vulnerability" => "Vulnerability",
    ],

    "Damage Types" => [
        "air"      => "Air",
        "bolt"     => "Bolt",
        "dark"     => "Dark",
        "earth"    => "Earth",
        "fire"     => "Fire",
        "ice"      => "Ice",
        "light"    => "Light",
        "physical" => "Physical",
        "poison"   => "Poison",
    ],

    "Item Categories & Properties" => [
        "accessory"  => "Accessory",
        "arcane"     => "Arcane",
        "armor"      => "Armor",
        "basic"      => "Basic",
        "bow"        => "Bow",
        "brawling"   => "Brawling",
        "dagger"     => "Dagger",
        "firearm"    => "Firearm",
        "flail"      => "Flail",
        "heavy"      => "Heavy",
        "martial"    => "Martial",
        "multi"      => "Multi",
        "rare"       => "Rare",
        "shield"     => "Shield",
        "spear"      => "Spear",
        "sword"      => "Sword",
        "thrown"     => "Thrown",
        "two-handed" => "Two-Handed",
        "two-weapon" => "Two-Weapon",
        "weapon"     => "Weapon",
    ],

    "Class Features & Subsystems" => [
        "arcana"      => "Arcana",
        "companion"   => "Companion",
        "dance"       => "Dances",
        "garden"      => "Garden",
        "gift"        => "Gifts",
        "ingredient"  => "Ingredients",
        "invocation"  => "Invocations",
        "module"      => "Modules",
        "symbol"      => "Symbols",
        "therioform"  => "Therioforms",
        "trade-point" => "Trade Point",
        "vehicle"     => "Vehicle",
        "verse"       => "Verses",
    ]
];