<?php

$filter_tags = [
    "Source" => [
        "core"                  => "Core",
        "high-fantasy"          => "High Fantasy",
        "natural-fantasy"       => "Natural Fantasy",
        "techno-fantasy"        => "Techno Fantasy",
        "fabula-ultima-bonus"   => "Fabula Ultima Bonus",
    ],

    "Classes" => [
        "any-class"    => "Any Class",
        "arcanist"     => "Arcanist",
        "chanter"      => "Chanter",
        "chimerist"    => "Chimerist",
        "commander"    => "Commander",
        "dancer"       => "Dancer",
        "darkblade"    => "Darkblade",
        "elementalist" => "Elementalist",
        "entropist"    => "Entropist",
        "esper"        => "Esper",
        "floralist"    => "Floralist",
        "fury"         => "Fury",
        "gourmet"      => "Gourmet",
        "guardian"     => "Guardian",
        "invoker"      => "Invoker",
        "loremaster"   => "Loremaster",
        "merchant"     => "Merchant",
        "mutant"       => "Mutant",
        "orator"       => "Orator",
        "pilot"        => "Pilot",
        "rogue"        => "Rogue",
        "sharpshooter" => "Sharpshooter",
        "spiritist"    => "Spiritist",
        "symbolist"    => "Symbolist",
        "tinkerer"     => "Tinkerer",
        "wayfarer"     => "Wayfarer",
        "weaponmaster" => "Weaponmaster",
    ],

    "Class Mechanics" => [
        "arcana"      => "Arcana",
        "companion"   => "Companion",
        "dance"       => "Dances",
        "focus"       => "Focus",
        "garden"      => "Garden",
        "gift"        => "Gifts",
        "ingredient"  => "Ingredients",
        "invocation"  => "Invocations",
        "module"      => "Modules",
        "symbol"      => "Symbols",
        "therioform"  => "Therioforms",
        "trade-point" => "Trade Points",
        "vehicle"     => "Vehicles",
        "verse"       => "Verses",
    ],

    "Turn Actions" => [
        "attack"       => "Attack",
        "equipment"    => "Equipment",
        "guard"        => "Guard",
        "hinder"       => "Hinder",
        "inventory"    => "Inventory",
        "objective"    => "Objective",
        "skill"        => "Skill",
        "spell"        => "Spell",
        "study"        => "Study",
    ],

    "Game Mechanics" => [
        "add-action"    => "Additional Action",
        "ask-question"  => "Ask a Question",
        "bond"          => "Bond",
        "clock"         => "Clock",
        "crisis"        => "Crisis",
        "critical"      => "Critical Success",
        "death-save"    => "Death Save Effect",
        "dispel-effect" => "Dispel a Scene Effect",
        "fabula-point"  => "Fabula Point",
        "fewer-actions" => "Fewer Actions",
        "free-attack"   => "Free Attack",
        "free-spell"    => "Free Spell",
        "flying"        => "Flying",
        "fumble"        => "Fumble",
        "reroll"        => "Reroll",
        "ritual"        => "Ritual",
        "species"       => "Species",
        "take-turn"     => "Take Immediate Turn",
        "taunt"         => "Taunt Effect",
        "traits"        => "Traits",
        "travel"        => "Travel",
        "zenit"         => "Zenit",
    ],

    "Attributes & Stats" => [
        "DEX"           => "Dexterity (DEX)",
        "INS"           => "Insight (INS)",
        "MIG"           => "Might (MIG)",
        "WLP"           => "Willpower (WLP)",
        "hp"            => "Hit Points",
        "mp"            => "Mind Points",
        "ip"            => "Inventory Points",
        "defense"       => "Defense",
        "magic-defense" => "Magic Defense",
        "initiative"    => "Initiative",
    ],

    "Affinities" => [
        "absorption"    => "Absorption",
        "ignore"        => "Ignore",
        "immunity"      => "Immunity",
        "resistance"    => "Resistance",
        "vulnerability" => "Vulnerability",
    ],

    "Damage Types" => [
        "air"      => "Air",
        "bolt"     => "Bolt",
        "dark"     => "Dark",
        "earth"    => "Earth",
        "fire"     => "Fire",
        "ice"      => "Ice",
        "light"    => "Light",
        "physical" => "Physical",
        "poison"   => "Poison",
        "untyped"  => "Untyped",
    ],

    "Status Conditions" => [
        "dazed"     => "Dazed",
        "shaken"    => "Shaken",
        "slow"      => "Slow",
        "weak"      => "Weak",
        "enraged"   => "Enraged",
        "poisoned"  => "Poisoned",
    ],

    "Equipment Types" => [
        "martial"       => "Martial",
        "non-martial"   => "Non-Martial",
        "accessory"     => "Accessory",
        "armor"         => "Armor",
        "shield"        => "Shield",
        "weapon"        => "Weapon",
    ],

    "Equipment Properties" => [
        "basic"         => "Basic",
        "rare"          => "Rare",
        "multi"         => "Multi",
        "one-handed"    => "One-Handed",
        "two-handed"    => "Two-Handed",
        "melee"         => "Melee",
        "ranged"        => "Ranged",
    ],

    "Weapon Categories" => [
        "arcane"        => "Arcane",
        "bow"           => "Bow",
        "brawling"      => "Brawling",
        "dagger"        => "Dagger",
        "firearm"       => "Firearm",
        "flail"         => "Flail",
        "heavy"         => "Heavy",
        "spear"         => "Spear",
        "sword"         => "Sword",
        "thrown"        => "Thrown",
    ],

    "Creature Species" => [
        "beast"         => "Beast",
        "construct"     => "Construct",
        "demon"         => "Demon",
        "elemental"     => "Elemental",
        "humanoid"      => "Humanoid",
        "monster"       => "Monster", 
        "plant"         => "Plant",
        "undead"        => "Undead",
    ],
];